// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Car
{
    public int CarId { get; set; }

    public string Make { get; set; }

    public string Model { get; set; }

    public int ManufactureYear { get; set; }

    public int? CarTypeId { get; set; }

    public string Color { get; set; }

    public int? Mileage { get; set; }

    public string LicensePlate { get; set; }

    public decimal AskingPrice { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public DateOnly? ListingDate { get; set; }

    public int? SellerId { get; set; }

    public string CarName { get; set; }

    public virtual CarType CarType { get; set; }

    public virtual User Seller { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}